I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 139, in script
    show screen force_mouse_move_1
  File "renpy/common/000statements.rpy", line 510, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen force_mouse_move_1 is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 139, in script
    show screen force_mouse_move_1
  File "C:\Users\Sabrina\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 1949, in execute
    self.call("execute")
  File "C:\Users\Sabrina\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 1937, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\Sabrina\Desktop\renpy-7.3.5-sdk\renpy\statements.py", line 277, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 510, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "C:\Users\Sabrina\Desktop\renpy-7.3.5-sdk\renpy\display\screen.py", line 1107, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen force_mouse_move_1 is not known.


Windows-8-6.2.9200
Ren'Py 7.3.5.606
Vanitas 1.0
Fri Aug 21 13:46:27 2020
