I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/office.rpy", line 1487, in script
    
ScriptError: could not find label 'next_step_with_bomb'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/office.rpy", line 1487, in script
    
  File "C:\Users\Sabrina\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 1697, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Sabrina\Desktop\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'next_step_with_bomb'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Vanitas 1.0
Thu Aug 20 05:38:27 2020
